FROM docker.io/oraclelinux:7.3
MAINTAINER tangfeixiong <tangfx128@gmail.com>
# Inspired by: Anastas Dancha <anapsix@random.io>, playniuniu@gmail.com, 
# and [Oracle Github-ed Java, Weblogic guide](https://github.com/oracle/docker-images)

# server JRE 8 "http://download.oracle.com/otn-pub/java/jdk/8u112-b15/server-jre-8u112-linux-x64.tar.gz"
# server JRE 7 "http://download.oracle.com/otn-pub/java/jdk/7u80-b15/server-jre-7u80-linux-x64.tar.gz"
# Java download location (default is Oracle Server JRE 7)
ARG java_pkg="http://172.17.4.1:48080/99-mirror/http%3A%2F%2Fdownload.oracle.com/otn-pub%2Fjava%2Fjdk%2F7u80-b15/server-jre-7u80-linux-x64.tar.gz"
# Oracle Fusion Middleware Weblogic "wls1213_dev_update3.zip"
ARG fmw_pkg="http://172.17.4.1:48080/99-mirror/http%3A%2F%2Fdownload.oracle.com/otn%2Fnt%2Fmiddleware%2F12c%2Fwls%2F1213/wls1213_dev_update3.zip"
# ARG rpm_pkg, a local fileserver destinations which packages are download by "download-oraclelinux7-rpm.sh"
ARG rpm_pkg="http://172.17.4.1:48080/99-mirror/%2E%2Eworkspace%2Fsrc%2Fgithub.com%2Fstackdocker%2Fweblogic-docker%2Fdownload%2Foraclelinux7%2Frpm"

# weblogic domain name (default is "base_domain").
ARG wls_domain_name
# weblogic admin username (default is "weblogic").
ARG wls_admin_username
# weblogic admin password (default is "weblogic1234%^&*")
ARG wls_admin_password
# weblogic procution mode (default is "prod")
# ARG wls_production_mode

COPY / /tmp/build/

ENV JAVA_HOME="/opt/java" \
    MW_HOME="/u01/oracle" \
    ORACLE_HOME="/u01/oracle" \
    WL_HOME="/u01/oracle/wlserver" \
    DOMAIN_NAME="${wls_domain_name:-base_domain}" \
    DOMAIN_HOME="/u01/oracle/user_projects/domains/${wls_domain_name:-base_domain}" \
    ADMIN_PORT="8001" \
    ADMIN_HOST="wlsadmin" \
    NM_PORT="5556" \
    MS_PORT="7001" \
    CONFIG_JVM_ARGS="-Dweblogic.security.SSL.ignoreHostnameVerification=true" \
    USER_MEM_ARGS="-Djava.security.egd=file:/dev/./urandom" \
    PATH=$PATH:/opt/java/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin:/u01/oracle/user_projects/domains/${wls_domain_name:-base_domain}/bin:/u01/oracle
# "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
### ENV PRODUCTION_MODE="${wls_production_mode:-'prod'}"
### ENV MEM_DEV_ARGS="-Xms512m -Xmx512m -XX:PermSize=64m -XX:MaxPermSize=256m"
### ENV DEBUG_PORT="8453"
### ENV DEBUG_FLAG="true"

RUN set -x \
    && temp_dir=/tmp/build \
# Install Oracle Server JRE package
    && mkdir -p $JAVA_HOME \
    && javaPkgSrc="${java_pkg:-'http://download.oracle.com/otn/java/jdk/7u80-b15/server-jre-7u80-linux-x64.tar.gz'}" \
    && if [[ -f $temp_dir/$javaPkgSrc ]]; then \
        tar -C $JAVA_HOME --strip-components=1 -zxf $temp_dir/$javaPkgSrc; \
        rm -f $temp_dir/$javaPkgSrc; \
    elif [[ ! "$javaPkgSrc" =~ https?://download\.oracle\.com/?.* ]]; then \
        curl -jkSL ${javaPkgSrc//%/%25} \
            | gunzip \
            | tar -x -C $JAVA_HOME --strip-components=1; \
    else \
        curl -jkSLH "Cookie: oraclelicense=accept-securebackup-cookie; " "$javaPkgSrc" \
            | gunzip \
            | tar -x -C "$JAVA_HOME" --strip-components=1; \
    fi \
    && javaSlim=" \
        README.html \
        release \
        THIRDPARTYLICENSEREADME*.txt \
        *src.zip \
        db/3RDPARTY \
        db/NOTICE \
        db/README-JDK.html \
        db/RELEASE-NOTES.html \
        db/bin/*.bat \
        db/lib/derbyLocale_de_DE.jar \
        db/lib/derbyLocale_es.jar \
        db/lib/derbyLocale_fr.jar \
        db/lib/derbyLocale_hu.jar \
        db/lib/derbyLocale_it.jar\
        db/lib/derbyLocale_ja_JP.jar \
        db/lib/derbyLocale_ko_KR.jar \
        db/lib/derbyLocale_pl.jar \
        db/lib/derbyLocale_pt_BR.jar \
        db/lib/derbyLocale_ru.jar \
        db/lib/derbyLocale_zh_TW.jar \
        jre/README \
        jre/THIRDPARTYLICENSEREADME*.txt \
        jre/Welcome.html \
        jre/plugin \
        jre/bin/javaws \
        jre/bin/jjs \
        jre/bin/keytool \
        jre/bin/orbd \
        jre/bin/pack200 \
        jre/bin/policytool \
        jre/bin/rmid \
        jre/bin/rmiregistry \
        jre/bin/servertool \
        jre/bin/tnameserv \
        jre/bin/unpack200 \
        jre/lib/javaws.jar \
        jre/lib/deploy* \
        jre/lib/desktop \
        jre/lib/*javafx* \
        jre/lib/*jfx* \
        jre/lib/amd64/libdecora_sse.so \
        jre/lib/amd64/libprism_*.so \
        jre/lib/amd64/libfxplugins.so \
        jre/lib/amd64/libglass.so \
        jre/lib/amd64/libgstreamer-lite.so \
        jre/lib/amd64/libjavafx*.so \
        jre/lib/amd64/libjfx*.so \
        jre/lib/ext/jfxrt.jar \
        jre/lib/nashorn.jar \
        jre/lib/oblique-fonts \
        jre/lib/plugin.jar \
        lib/*javafx* \
        lib/missioncontrol \
        lib/visualvm \
        man/ja \
        man/ja_JP.UTF-8 \
    " \
    && for i in $javaSlim; do \
        rm -rf $JAVA_HOME/$i; \
    done \ 
# Install Oracle Weblogic package
    && mkdir -p /u01 \
    && chmod a+xr /u01 \
    && useradd -b /u01 -m -s /bin/bash oracle \
    && echo oracle:oracle | chpasswd \
    && fmwPkgSrcDir=$(mktemp -d) \
    && if [ -f $temp_dir/$fmw_pkg ]; then \
        mv $temp_dir/$fmw_pkg $fmwPkgSrcDir/wls.zip; \
    else \
        curl -jkSL ${fmw_pkg//%/%25} -o $fmwPkgSrcDir/wls.zip; \
    fi \
    && cd $fmwPkgSrcDir \
    && $JAVA_HOME/bin/jar xf wls.zip \
    && mv wls12130/* $ORACLE_HOME \
    ### wls_tmpdir=$(mktemp --dry-run)
    ### unzip -qd $wls_tmpdir $fmwPkgSrcDir/wls.zip
    ### wls_path=$(basename $(ls -d $wls_tmpdir/wls*))
    ### mv $wls_tmpdir/$wls_path $MW_HOME
    ### rm -rf $wls_tmpdir
    ### export PATH=$PATH:$JAVA_HOME/bin:$MW_HOME/oracle_common/common/bin:$MW_HOME/wlserver/common/bin:$DOMAIN_HOME/bin:$MW_HOME
    && cd $ORACLE_HOME \
    && rm -rf $fmwPkgSrcDir \    
    && sh configure.sh -silent \
    && find $ORACLE_HOME -name "*.sh" -exec chmod a+x {} \; \
    && chown oracle:oracle -R /u01 \
    ### . $MW_HOME/wlserver/server/bin/setWLSEnv.sh
    ### for i in $(ls $temp_dir/container-scripts/{*.py,*.sh}); do 
    ###    sed -i "s%/u01/oracle/%$MW_HOME/%g" $i; 
    ### done 
    && mv $temp_dir/container-scripts/* $ORACLE_HOME \
    && ADMIN_PASSWORD=${wls_admin_password:-weblogic1234%^&*} $ORACLE_HOME/wlst $ORACLE_HOME/create-wls-domain.py \
    && mkdir -p $DOMAIN_HOME/servers/AdminServer/security \
    && echo -e "username=${wls_admin_username:-weblogic}\npassword=${wls_admin_password:-weblogic1234%^&*}" \
        | tee $DOMAIN_HOME/servers/AdminServer/security/boot.properties \
    && echo -e "\n. $DOMAIN_HOME/bin/setDomainEnv.sh\n\nexport PATH=$PATH" \
        | tee -a $HOME/.bashrc \
    && cp $MW_HOME/commEnv.sh $MW_HOME/wlserver/common/bin/commEnv.sh \
    && rm $MW_HOME/create-wls-domain.py $MW_HOME/jaxrs2-template.jar \
    && rm -rf $temp_dir/container-scripts \
    && fmwSlim=" \
        README_WIN* \
        configure.cmd \
        coherence/bin/*.cmd \
        coherence/bin/optimize.reg \
        coherence/bin/readme \
        oracle_common/bin/*.bat \
        oracle_common/common/bin/*.cmd \
        oracle_common/common/modules/datadirect/*.dll \
        oracle_common/common/modules/mysql-connector-java-commercial-5.1.22/docs \
        oracle_common/common/modules/mysql-connector-java-commercial-5.1.22/CHANGES \
        oracle_common/common/modules/mysql-connector-java-commercial-5.1.22/*README* \
        oracle_common/common/modules/oracle.fmwconfig.common.wls.help/wl???_de.* \
        oracle_common/common/modules/oracle.fmwconfig.common.wls.help/wl???_es.* \
        oracle_common/common/modules/oracle.fmwconfig.common.wls.help/wl???_fr.* \
        oracle_common/common/modules/oracle.fmwconfig.common.wls.help/wl???_it.* \
        oracle_common/common/modules/oracle.fmwconfig.common.wls.help/wl???_ja.* \
        oracle_common/common/modules/oracle.fmwconfig.common.wls.help/wl???_ko.* \
        oracle_common/common/modules/oracle.fmwconfig.common.wls.help/wl???_pt_BR.* \
        oracle_common/common/modules/oracle.fmwconfig.common.wls.help/wl???_zh_TW.* \
        oracle_common/common/modules/org.apache.ant_1.9.2/bin/*.bat \
        oracle_common/common/modules/org.apache.ant_1.9.2/bin/*.cmd \
        oracle_common/common/modules/org.apache.ant_1.9.2/manual \
        oracle_common/common/modules/org.apache.ant_1.9.2/INSTALL \
        oracle_common/common/modules/org.apache.ant_1.9.2/README \
        oracle_common/common/modules/org.apache.ant_1.9.2/WHATSNEW \ 
        oracle_common/common/modules/org.apache.maven_3.0.5/bin/*.bat \
        wlserver/common/bin/*.cmd \
        wlserver/server/bin/international \
        wlserver/server/bin/*.exe \
        wlserver/server/bin/*.dll \
        wlserver/server/bin/*.lib \
        wlserver/server/bin/*.cmd \
        ### wlserver/server/db2
        ### wlserver/server/informix
        ### wlserver/server/sybase
        wlserver/server/include/aixppc* \
        wlserver/server/include/hp-ux \
        wlserver/server/include/lnx_s* \
        wlserver/server/include/lnxi* \
        wlserver/server/include/win32 \
        wlserver/server/include/platform/aixppc* \
        wlserver/server/include/platform/hp-ux \
        wlserver/server/include/platform/lnx_s* \
        wlserver/server/include/platform/lnxi* \
        wlserver/server/include/platform/win32 \
        wlserver/server/lib/weblogic-de.* \
        wlserver/server/lib/weblogic-es.* \
        wlserver/server/lib/weblogic-fr.* \
        wlserver/server/lib/weblogic-it.* \
        wlserver/server/lib/weblogic-js.* \
        wlserver/server/lib/weblogic-ko.* \
        wlserver/server/lib/weblogic-pt_BR.* \
        wlserver/server/lib/weblogic-zh_TW.* \
        wlserver/server/lib/wlw-langx-jx.* \
        wlserver/server/lib/wlw-langx-ko.* \
        wlserver/server/lib/wlw-langx-zh_TW.* \
        wlserver/server/locale/C/aix-*,hpux-* \
        wlserver/server/locale/C/linux-i* \
        wlserver/server/locale/C/linux-s* \
        wlserver/server/locale/C/solaris-* \
        wlserver/server/locale/C/win* \
        wlserver/server/native/linux/i686 \
        wlserver/server/native/win \
        wlserver/sip/server/native/linux/i686 \
        wlserver/sip/server/native/solaris \
    " \
    && for i in $fmwSlim; \
        do rm -rf $MW_HOME/$i; \
    done \
# install locale RPM package
    && install_PKGs=" \
        ### unzip
        ### bsdtar
        glibc-common \
    " \
    ### yum install -y $install_PKGs 
    ### rpm -V $install_PKGs 
    ### yum clean all 
    && install_RPMs=" \
glibc-2.17-157.el7_3.1.x86_64.rpm \
glibc-common-2.17-157.el7_3.1.x86_64.rpm \
### bsdtar-3.1.2-10.el7_2.x86_64.rpm
### libarchive-3.1.2-10.el7_2.x86_64.rpm
### lzo-2.06-8.el7.x86_64.rpm
### unzip-6.0-16.el7.x86_64.rpm
    " \
    && rpmPkgSrcDir="$(mktemp -d)" \
    && cd "$rpmPkgSrcDir" \
    && for i in $install_RPMs; do \
        curl -jkSL "${rpm_pkg//%/%25}/${i##*( )}" -O; \
    done \
    && rpm -Uvh * \
    && rm -rf "$rpmPkgSrcDir" \
    && localedef -c -i zh_CN -f UTF-8 zh_CN.UTF-8 \
    && rm -f /etc/localtime \
    && ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
# Finally
    ### install_PKGs="
    ###    unzip
    ### "
    ### yum remove -y $install_PKGs
    && cd / \
    && rm -rf $temp_dir

### WORKDIR /u01/oracle

# Default to UTF-8 file.encoding
# ENV LANG zh_CN.UTF-8
# ENV LC_ALL zh_CN.UTF-8

ENV JAVA_OPTIONS="$JAVA_OPTIONS -Xms512m -Xmx512m -XX:PermSize=128m -XX:MaxPermSize=512m"

### VOLUME ["$DOMAIN_HOME/autodeploy"]

### EXPOSE $ADMIN_PORT $NM_PORT $MS_PORT $DEBUG_PORT
EXPOSE $ADMIN_PORT $NM_PORT $MS_PORT
CMD ["startWebLogic.sh"]
