apiVersion: v1
kind: Pod
metadata:
  labels:
    run: weblogic1213
  name: weblogic1213
  namespace: default
spec:
  containers:
  - image: 10.64.33.81:5000/weblogic:domain_12.1.3-serverjre7-ol7
    imagePullPolicy: IfNotPresent
    name: weblogic1213
    resources: {}
    volumeMounts:
    - mountPath: /opt/fmw/user_projects/domains/base_domain/autodeploy
      name: autodeploy
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  securityContext: {}
  volumes:
  - name: autodeploy
    hostPath:
      path: /tmp/k8s-vol/weblogic1213/autodeploy
