apiVersion: v1
kind: Service
metadata:
  labels:
    run: weblogic1213
  name: wls
  namespace: default
spec:
  # clusterIP: 10.123.245.183
  # portalIP: 10.123.245.183
  ports:
  - # nodePort: 31647
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    run: weblogic1213
  sessionAffinity: None
  type: NodePort
